### ISSUE TITLE
Add some utility functions/macros for deserializing multiple objects.

### ISSUE THREAD

**Issue by GabrielCastro** [GabrielCastro/neon-serde#2]
We can probably eliminate some of the boiler plate.
ie: go from something like 
```rust
 call.arguments.require(scope, 0)?.check::<JsInteger>()
```
to
```rust
let (foo, bar, baz): (i32, String, MyType) = call.arguments.deserialize()?
```
or
```rust
let (foo, bar, baz) = deserialize!(scope, call, (i32, String, MyType));
```

using a method looks like it isn't too possible without https://github.com/rust-lang/rfcs/issues/376 but a macro should work.

**Comment by matklad** [comment]
>using a method looks like it isn't too possible without rust-lang/rfcs#376 but a macro should work.

I think it should be possible by implementing a custom trait for tuples of deserializable objects up to certain size.

Something like

```
trait FromArguments {
  fn from_arguments(args: NeonArguments) -> Self
}

fn parse<T: FromArguments>(args: NeonArguments) -> T { FromArguments::from_arguments(args) }

impl FromArguments for () { ... }

impl<T1: Deserialize> FromArguments for (T1,) { ... }

impl<T1: Deserialize, T2: Deserialize> FromArguments for (T1, T2) { ... }

// probably up to T1...T12, probably macro generated.
```
