### ISSUE TITLE
Compatibility with neon 0.2

### ISSUE THREAD

**Issue by matklad** [GabrielCastro/neon-serde#21]
Hey, looks like a new version of neon was released recently! Would be cool to upgrade neon seeds to that.

**Comment by apendleton** [comment]
I've started poking at this, but it's taking a bit because I don't really know what I'm doing. Lifetime management in this library seems both tricky and to need to change quite a bit with the Scope -> Context transition in 0.2. Would be happy to collaborate though if others are working on it.

**Comment by apendleton** [comment]
@matklad gave it a go in #22
