### ISSUE TITLE
Lifetimes bounds for `to_value` `from_handle` could probably be wrong.

### ISSUE THREAD

**Issue by matklad** [GabrielCastro/neon-serde#4]
Hi! I am trying to write a function, using both `to_value` and `from_handle`. The function looks like this:

```Rust
fn foo<'c>(call: Call<'c>) -> JsResult<'c, JsValue> {
    let scope = call.scope;
    let result: () = {
        let arg: Handle<'c, JsValue> = call.arguments.require(scope, 0)?;
        let () = from_handle(arg, scope)?;
        ()
    };
    let result: Handle<'c, JsValue> = to_value(&result, scope)?;
    Ok(result)
}
```

I *think* it should compile, but I am getting lifetime errors:

```
error[E0499]: cannot borrow `*scope` as mutable more than once at a time
   --> src/lib.rs:291:57
    |
288 |         let () = from_handle(arg, scope)?;
    |                                   ----- first mutable borrow occurs here
...
291 |     let result: Handle<'c, JsValue> = to_value(&result, scope)?;
    |                                                         ^^^^^ second mutable borrow occurs here
292 |     Ok(result)
293 | }
    | - first borrow ends here
```

If I change signatres of `from_handle`/`to_value` like this, the error goes away:

```Rust
pub fn from_handle<'a, T>(
    input: Handle<'a, js::JsValue>,
    scope: &/*'a*/ mut RootScope<'a>,
) -> LibResult<T>
where
    T: serde::Deserialize<'a> + ?Sized,
{
    unimplemented!()
}


pub fn to_value<'value, 'shandle, 'scope: 'shandle, V: Serialize + ?Sized, S: Scope<'scope>>(
    value: &'value V,
    scope: &/*'shandle*/ mut S,
) -> LibResult<Handle</*'shandle*/ 'scope, js::JsValue>> {
    unimplemented!()
}
```

That is, for `'a` in `Handle<'a, JsValue>`, we use `'a` from `Scope<'a>` , and not the `&mut` one, the same way `JsInteger::new` does.

Unfortunately, I am not super familiar with serde, so I was unable to qucikly check if I can write the impl for Ser&De....

**Comment by GabrielCastro** [comment]
I've noticed this I've tried to solve it sever times, but I'm still not sure how to my 2 starting points have been using [DeserializeOwned]https://docs.serde.rs/serde/de/trait.DeserializeOwned.html) which will hopefully help a bit, and using [Scope::chained](https://api.neon-bindings.com/neon/scope/trait.scope#tymethod.chained) so we can just take a non mut scope, but it introduces new lifetimes to keep track of.
